### ISSUE TITLE
remove/adding integration throws an exception due to network issue

### ISSUE THREAD

**Issue by marcschmiedchen** [marcschmiedchen/home-assistant-wolf_ism8#59]
Logger: homeassistant.config_entries
Quelle: config_entries.py:604
Erstmals aufgetreten: 09:35:44 (1 Vorkommnisse)
Zuletzt protokolliert: 09:35:44

Error setting up entry ISM8 for wolf
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wolf/__init__.py", line 42, in async_setup_entry
    await task
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1572, in create_server
    raise OSError(err.errno, msg) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 12004): address in use

**Comment by marcschmiedchen** [comment]
shutting down server when removing integration
